version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - gir1.2-glib-2.0
    - libffi-dev
    - libgirepository1.0-dev
    - libglib2.0-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .