version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  apt_packages:
    - gir1.2-glib-2.0
    - libffi-dev
    - libglib2.0-dev
    - python-gi-dev
    - libcairo-gobject2
    - libcairo2-dev

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
